development:
  bucket: evolve-ca
  access_key_id: AKIAIOXAGEK4YWOTQBXQ
  secret_access_key: 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
test:
  bucket: evolve-ca
  access_key_id: AKIAIOXAGEK4YWOTQBXQ
  secret_access_key: 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
production:
  bucket: evolve-ca
  access_key_id: AKIAIOXAGEK4YWOTQBXQ
  secret_access_key: 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


